name: Build Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Endstone
      run: |
        python -m pip install --upgrade pip
        pip install endstone
        
    - name: Configure CMake
      run: |
        python -c "import endstone, os, subprocess, sys; dir=os.path.dirname(endstone.__file__); cmd=['cmake', '-B', 'build', '-S', '.', '-DCMAKE_BUILD_TYPE=Release', f'-DCMAKE_PREFIX_PATH={dir}']; print('Running:', ' '.join(cmd)); sys.exit(subprocess.call(cmd))"

      
    - name: Build Plugin
      run: cmake --build build --config Release
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rsnhybridplugin-${{ runner.os }}
        path: |
          build/**/*.so
          build/**/*.dll
          build/Release/*.dll
