name: Build Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install -y libc++-18-dev libc++abi-18-dev

    - name: Install Ninja
      run: |
        python -m pip install --upgrade pip
        pip install ninja

    - name: Configure CMake
      shell: bash
      env:
        CC: clang-18
        CXX: clang++-18
      run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release
      
    - name: Build Plugin
      shell: bash
      run: |
        if ! cmake --build build --config Release > build_log.txt 2>&1; then
           echo "::error::Compilation failed! Tail of log:"
           tail -n 50 build_log.txt | while read line; do
               echo "::error::$line"
           done
           exit 1
        fi
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rsnhybridplugin-${{ runner.os }}
        path: |
          build/**/*.so
          build/**/*.dll
          build/Release/*.dll
